/*
 * Gunbot REST API
 * The Gunbot REST API enables you to programmatically interact with Gunbot, a self hosted trading bot for crypto, ETFs and stocks, allowing automation and integration with your own applications and services. It gives you a single API with which you can control trading operations on many exchanges.  The API accepts and returns data in JSON format. It uses standard HTTP response codes to indicate request outcomes: - **200 OK**: The request was successful. - **400 Bad Request**: The request was invalid or cannot be processed. - **401 Unauthorized**: Authentication failed, or the user lacks necessary permissions. - **500 Internal Server Error**: A server-side error occurred.  **Gunbot Workflow:** To automate trading for any pair using the API, follow these steps: 1. Add the trading pair to the configuration with a valid strategy. 2. Start the core to activate trading operations. After completing these steps, you can access API endpoints for market data and trading actions. Gunbot will actively monitor and execute strategies for the specified pairs.  **Encryption Helpers:** Gunbot uses password encryption. Refer to the original documentation for encryption helper snippets in JavaScript (Browser/Node.js), Bash, and Python. 
 *
 * OpenAPI spec version: v1
 * Contact: support@gunbot.freshdesk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GunbotRestApi);
  }
}(this, function(expect, GunbotRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AuthStatusResponse', function() {
      beforeEach(function() {
        instance = new GunbotRestApi.AuthStatusResponse();
      });

      it('should create an instance of AuthStatusResponse', function() {
        // TODO: update the code to test AuthStatusResponse
        expect(instance).to.be.a(GunbotRestApi.AuthStatusResponse);
      });

      it('should have the property code (base name: "code")', function() {
        // TODO: update the code to test the property code
        expect(instance).to.have.property('code');
        // expect(instance.code).to.be(expectedValueLiteral);
      });

      it('should have the property isDemo (base name: "isDemo")', function() {
        // TODO: update the code to test the property isDemo
        expect(instance).to.have.property('isDemo');
        // expect(instance.isDemo).to.be(expectedValueLiteral);
      });

      it('should have the property isRegistered (base name: "isRegistered")', function() {
        // TODO: update the code to test the property isRegistered
        expect(instance).to.have.property('isRegistered');
        // expect(instance.isRegistered).to.be(expectedValueLiteral);
      });

      it('should have the property isTwoFA (base name: "isTwoFA")', function() {
        // TODO: update the code to test the property isTwoFA
        expect(instance).to.have.property('isTwoFA');
        // expect(instance.isTwoFA).to.be(expectedValueLiteral);
      });

      it('should have the property metamask (base name: "metamask")', function() {
        // TODO: update the code to test the property metamask
        expect(instance).to.have.property('metamask');
        // expect(instance.metamask).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property message (base name: "message")', function() {
        // TODO: update the code to test the property message
        expect(instance).to.have.property('message');
        // expect(instance.message).to.be(expectedValueLiteral);
      });

    });
  });

}));
